// frontend/pages/vkapp/idea.jsx

import React from 'react'
import Page from '../../components/page'
import gate from '../../modules/gate'

export default class Screen extends React.Component {
    constructor () {
        super();
        this.state = {
            me: null,
            idea: null,
            search: '',
        };

        if ('undefined' !== typeof window) {
            const url = new URL(location.href);
            this.idea_id = url.searchParams.get('idea_id');
        }
    }

    async componentDidMount () {
        const me = await gate.ask('/users/me');
        this.setState({me});

        const idea = await gate.ask('/ideas/' + this.idea_id);
        this.setState({idea});

        if ('undefined' !== typeof window) {
            this.setState({search: window.location.search.split('&hash=')[0] + '&hash='});
        }
    }

    render () {
        const {me, idea, search} = this.state;
        const vkInfo = me && me.vkInfo || {};

        return (
            <Page>
                <a href={'/vkapp' + search}>к списку</a><br />
                {idea && (
                    <div>
                        <div>
                            <br />
                            {idea.parentIdeas && idea.parentIdeas.map((o, n) => (
                                <a key={n} href={'/vkapp/idea' + search + '&idea_id=' + o._id}> {o.title} -> </a>
                            ))}
                        </div>
                        <h2>{idea.title}</h2>
                        <p>{idea.description}</p>
                        <div>
                            Автор: {idea.author}<br />
                            Дата содания: {(new Date(idea.createdAt || 0)).toISOString()}<br />
                        </div>
                        <br />
                        <div>
                            <button onClick={this.vote.bind(this, idea._id, 3)}>Голосовать За</button>
                            <button onClick={this.vote.bind(this, idea._id, 4)}>Голосовать Против</button>
                            <button onClick={this.vote.bind(this, idea._id, 2)}>Пропустить</button>
                        </div>
                        <br />
                        <div>
                            За: {idea.votesPlus}<br />
                            Против: {idea.votesMinus}<br />
                            Воздержались: {idea.skips}<br />
                            Всего просмотров: {idea.views}<br />
                        </div>
                        
                        <h3>Аргументы за ({idea.ideasPlusCount})</h3>
                        {idea.ideasPlus && idea.ideasPlus.map((o, n) => (
                            <div key={n}>
                                <a href={'/vkapp/idea' + search + '&idea_id=' + o._id}>{o.title}</a>
                            </div>
                        ))}
                        <a href={'/vkapp/idea-add' + search + `&parent_idea_id=${idea._id}&idea_type=3`}>[добавить]</a><br />
                        
                        <h3>Аргументы против ({idea.ideasMinusCount})</h3>
                        {idea.ideasMinus && idea.ideasMinus.map((o, n) => (
                            <div key={n}>
                                <a href={'/vkapp/idea' + search + '&idea_id=' + o._id}>{o.title}</a>
                            </div>
                        ))}
                        <a href={'/vkapp/idea-add' + search + `&parent_idea_id=${idea._id}&idea_type=4`}>[добавить]</a><br />
                        
                        <h3>Комментарии ({idea.commentsCount})</h3>
                        {idea.comments && idea.comments.map((o, n) => (
                            <div key={n}>
                                <a href={'/vkapp/idea' + search + '&idea_id=' + o._id}>{o.title}</a>
                            </div>
                        ))}
                        <a href={'/vkapp/idea-add' + search + `&parent_idea_id=${idea._id}&idea_type=1`}>[добавить]</a><br />
                        
                        <h3>Альтернативы ({idea.alternativesCount})</h3>
                        {idea.alternatives && idea.alternatives.map((o, n) => (
                            <div key={n}>
                                <a href={'/vkapp/idea' + search + '&idea_id=' + o._id}>{o.title}</a>
                            </div>
                        ))}
                        <a href={'/vkapp/idea-add' + search + `&parent_idea_id=${idea._id}&idea_type=2`}>[добавить]</a><br />
                        
                        <h3>Планы реализации ({idea.implementationsCount})</h3>
                        {idea.implementations && idea.implementations.map((o, n) => (
                            <div key={n}>
                                <a href={'/vkapp/idea' + search + '&idea_id=' + o._id}>{o.title}</a>
                            </div>
                        ))}
                        <a href={'/vkapp/idea-add' + search + `&parent_idea_id=${idea._id}&idea_type=5`}>[добавить]</a><br />
                    </div>
                )}
            </Page>
        );
    }

    async vote (ideaId, voteType) {
        const query = {ideaId, voteType};
        const res = await gate.ask('/vote', {
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            method: 'POST',
            body: JSON.stringify(query),
        });

        const idea = await gate.ask('/ideas/' + this.idea_id);
        this.setState({idea});
    }
}

// client/src/pages/idea.vue
<template>
	<div class="IdeaPage VkPage">
		<div v-if="!idea" class="anch" @click="$router.push('/ideas')">&lt; список тем</div>
		<div v-if="idea">
			<div class="header breadcrumbs">
				<span class="anch" @click="$router.push('/ideas')">
					<span v-if="!idea.parentIdeas || !idea.parentIdeas.length">&lt;</span>
					список тем
				</span>
				<template v-for="par in idea.parentIdeas">
					&gt;
					<span class="anch" v-text="par.title" @click="$router.push('/idea/' + par._id)" :key="par._id"></span>
				</template>
			</div>
			<div class="title h2" v-text="idea.title"></div>
			<div class="description" v-text="idea.description"></div>
			<div class="created-area">
				<a v-text="idea.author.name" class="anch" :href="authorUrl" target="_blank"></a>,
				<span v-text="datetime" class="hint"></span>
			</div>
			<div class="actions row" v-if="!this.idea.myVote || this.revote">
				<button @click="vote(3)" class="option" :class="{active: this.idea.myVote === 3}">
					Голосовать За
				</button>
				<button @click="vote(2)" class="option" :class="{active: this.idea.myVote === 2}">
					Пропустить
				</button>
				<button @click="vote(4)" class="option" :class="{active: this.idea.myVote === 4}">
					Голосовать Против
				</button>
			</div>
			<div class="revote anch" v-if="this.idea.myVote && !this.revote" @click="onClickRevote">переголосовать</div>
			<div class="stats row" v-if="this.idea.myVote">
				<!--<div class="stat-box">-->
					<!--<div class="count" v-text="acceptance"></div>-->
					<!--<div class="label">одобрение</div>-->
				<!--</div>-->
				<div class="stat-box plus" :class="{active: this.idea.myVote === 3}">
					<div class="count" v-text="idea.votesPlusCount"></div>
					<div class="label">поддержали</div>
				</div>
				<div class="stat-box neutral" :class="{active: this.idea.myVote === 2}">
					<div class="count" v-text="idea.skipsCount"></div>
					<div class="label">пропустили</div>
				</div>
				<div class="stat-box minus" :class="{active: this.idea.myVote === 4}">
					<div class="count" v-text="idea.votesMinusCount"></div>
					<div class="label">возразили</div>
				</div>
				<!--<div class="stat-box">-->
					<!--<div class="count" v-text="relevance"></div>-->
					<!--<div class="label">актуальность</div>-->
				<!--</div>-->
			</div>
			<section>
				<div class="hr wide" />
				<div class="row">
					<div class="half-area plus">
						<div class="area-title">
							<span class="h2">Комментарии &laquo;За&raquo;</span>
							<span class="hint count" v-if="idea.ideasPlusCount" v-text="'(' +idea.ideasPlusCount + ')'"></span>
							<button class="add-btn" @click="$router.push(`/idea-add?type=3&parent=${idea._id}`)">Добавить</button>
						</div>
						<ArgumentInDetails v-for="child in idea.ideasPlus" :idea="child" :key="child._id" @update="fetch"></ArgumentInDetails>
					</div>
					<div class="vr main" />
					<div class="half-area minus">
						<div class="area-title">
							<span class="h2">Комментарии &laquo;Против&raquo;</span>
							<span class="hint count" v-if="idea.ideasMinusCount" v-text="'(' +idea.ideasMinusCount + ')'"></span>
							<button class="add-btn" @click="$router.push(`/idea-add?type=4&parent=${idea._id}`)">Добавить</button>
						</div>
						<ArgumentInDetails v-for="child in idea.ideasMinus" :idea="child" :key="child._id" @update="fetch"></ArgumentInDetails>
					</div>
				</div>
				<!--<div class="anch">загрузить ещё...</div>-->
			</section>
			<!--section class="comments-area">
				<div class="h1">Комментарии<span v-if="idea.commentsCount" v-text="' (' +idea.commentsCount + ')'"></span></div>
				<CommentInDetails v-for="child in idea.comments" :idea="child" :key="child._id"></CommentInDetails>
				<button @click="$router.push(`/idea-add?type=1&parent=${idea._id}`)">Добавить</button>
			</section-->
			<!--<div v-text="idea"></div>-->
		</div>
	</div>
</template>

<script>
	import gate from '../modules/gate'
	import {renderDatetime} from '../modules/decorators'
	import ArgumentInDetails from '@/components/argument_in_details.vue';
	import CommentInDetails from '@/components/comment_in_details.vue';

	export default {
		components: {
			ArgumentInDetails,
			CommentInDetails,
		},
		props: ['id'],
		data () {
			return {
				initPromise: this.fetch(),
				idea: null,

				revote: false,
			};
		},
		watch: {
			id () {
				this.initPromise = this.fetch();
			}
		},
		computed: {
			datetime () {
				const date = new Date(this.idea.createdAt);
				return renderDatetime(date);
			},
			authorUrl () {
				return this.idea.author && `https://vk.com/id${this.idea.author.vkUid}`;
			},
			acceptance () {
				const {idea} = this;
				const val = idea.votesPlusCount / (idea.votesPlusCount + idea.votesMinusCount);
				if (val >= 0) {
					return Math.round(100 * val) + '%';
				} else {
					return '-';
				}
			},
			relevance () {
				const {idea} = this;
				const val = (idea.votesPlusCount + idea.votesMinusCount) / (idea.votesPlusCount + idea.votesMinusCount + idea.skipsCount);
				if (val >= 0) {
					return Math.round(100 * val) + '%';
				} else {
					return '-';
				}
			},
		},
		methods: {
			async fetch () {
				this.idea = await gate.ask(`/ideas/${this.id}`);
				this.revote = false;
			},
			async vote (voteType) {
				const query = {
					ideaId: this.idea._id,
					voteType,
				};
				await gate.ask('/vote', {
					headers: {
						'Accept': 'application/json',
						'Content-Type': 'application/json'
					},
					method: 'POST',
					body: JSON.stringify(query),
				});
				await this.fetch();
				this.revote = false;
			},
			onClickRevote () {
				this.revote = true;
			},
		},
	};
</script>

<style scoped lang="less" src="./idea.less"></style>
